import type { Metadata } from 'next'
import './style/globals.css';
import { ThemeProvider } from "@/components/providers/theme-provider"
import { DebugPanel } from '@/components/common/debug-panel';



export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <html lang="en">
    <body>          
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
        <DebugPanel />
      </ThemeProvider>
    </body>
  </html>
}
